In [81]:
# Question 2

In [1]:
T1 = [1 0 0;0 1 0; 3 -1 1]

3×3 Matrix{Int64}:
 1   0  0
 0   1  0
 3  -1  1

In [2]:
T2 = [1 0 0;0 1 0; -3 1 1]

3×3 Matrix{Int64}:
  1  0  0
  0  1  0
 -3  1  1

In [3]:
theta = pi/5

0.6283185307179586

In [5]:
R = [cos(theta) sin(theta) 0; -sin(theta) cos(theta) 0; 0 0 1]

3×3 Matrix{Float64}:
  0.809017  0.587785  0.0
 -0.587785  0.809017  0.0
  0.0       0.0       1.0

In [10]:
z = [2, 2,1]

3-element Vector{Int64}:
 2
 2
 1

In [25]:
A = T1 * R * T2

3×3 Matrix{Float64}:
  0.809017   0.587785  0.0
 -0.587785   0.809017  0.0
  0.0148362  1.95434   1.0

In [29]:
"""
    lufact(A)

Compute the LU factorization of square matrix `A`, returning the
factors.
"""
function lufact(A)
    n = size(A,1)
    L = diagm(ones(n))   # ones on main diagonal, zeros elsewhere
    U = zeros(n,n)
    Aₖ = float(copy(A))

    # Reduction by outer products
    for k in 1:n-1
        U[k,:] = Aₖ[k,:]
        L[:,k] = Aₖ[:,k]/U[k,k]
        Aₖ -= L[:,k]*U[k,:]'
    end
    U[n,n] = Aₖ[n,n]
    return LowerTriangular(L),UpperTriangular(U)
end

lufact

In [76]:
L, U = lufact(A)

([1.0 0.0 0.0; -0.7265425280053609 1.0 0.0; 0.01833859550599218 1.5723727512523664 1.0], [0.8090169943749475 0.5877852522924731 0.0; 0.0 1.2360679774997898 0.0; 0.0 0.0 1.0])

In [20]:
using LinearAlgebra

In [46]:
L

3×3 LowerTriangular{Float64, Matrix{Float64}}:
  1.0         ⋅        ⋅ 
 -0.726543   1.0       ⋅ 
  0.0183386  1.57237  1.0

In [47]:
U

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 0.809017  0.587785  0.0
  ⋅        1.23607   0.0
  ⋅         ⋅        1.0

In [77]:
b = A * z
n = 3
for i in 1:n-1
    for j in i+1:n
        b[j] -= L[j,i] * b[i]
        L[j,:] -= L[j,i] * L[i,:]
    end
end
b

3-element Vector{Float64}:
 2.793604493334841
 2.4721359549995796
 0.9999999999999996

In [78]:
for i in n:-1:1
    b[i] /= U[i,i]
    U[i,:] /= U[i,i]
    for j in i-1:-1:1
        b[j] -= U[j,i] * b[i]
        U[j,:] -= U[j,i] * L[i,:]
    end
end
x = b
x - z

3-element Vector{Float64}:
  0.0
  0.0
 -4.440892098500626e-16

In [79]:
L

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅ 
 0.0  1.0   ⋅ 
 0.0  0.0  1.0

In [80]:
U

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.0  0.0
  ⋅   1.0  0.0
  ⋅    ⋅   1.0

In [82]:
# Question 3

In [92]:
A = [1 0 0 0 10^20; 1 1 0 0 0; 0 1 1 0 0;0 0 1 1 0; 0 0 0 1 0]

5×5 Matrix{Int64}:
 1  0  0  0  7766279631452241920
 1  1  0  0                    0
 0  1  1  0                    0
 0  0  1  1                    0
 0  0  0  1                    0

In [93]:
x_hat = [0, 1/3, 2/3, 1, 4/3]

5-element Vector{Float64}:
 0.0
 0.3333333333333333
 0.6666666666666666
 1.0
 1.3333333333333333

In [94]:
function LU_solve(A, b)
    n = size(A,1)
    L, U = lufact(A)
    for i in 1:n-1
        for j in i+1:n
            b[j] -= L[j,i] * b[i]
            L[j,:] -= L[j,i] * L[i,:]
        end
    end
    for i in n:-1:1
        b[i] /= U[i,i]
        U[i,:] /= U[i,i]
        for j in i-1:-1:1
            b[j] -= U[j,i] * b[i]
            U[j,:] -= U[j,i] * L[i,:]
        end
    end
    return b
end

LU_solve (generic function with 1 method)

In [95]:
b = A * x_hat

5-element Vector{Float64}:
 1.0355039508602989e19
 0.3333333333333333
 1.0
 1.6666666666666665
 1.0

In [96]:
x = LU_solve(A, b)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 1.3333333333333333

In [97]:
# Question 4

In [98]:
A = [1 1 0 1 0 0; 0 1 1 0 1 0; 0 0 1 1 0 1; 1 0 0 1 1 0; 1 1 0 0 1 1; 0 1 1 0 0 1]

6×6 Matrix{Int64}:
 1  1  0  1  0  0
 0  1  1  0  1  0
 0  0  1  1  0  1
 1  0  0  1  1  0
 1  1  0  0  1  1
 0  1  1  0  0  1

In [99]:
L, U = lufact(A)

([1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 1.0 0.0 … 1.0 0.0; 0.0 1.0 … 1.0 1.0], [1.0 1.0 … 0.0 0.0; 0.0 1.0 … 1.0 0.0; … ; 0.0 0.0 … -1.0 2.0; 0.0 0.0 … 0.0 -1.0])

In [100]:
L

6×6 LowerTriangular{Float64, Matrix{Float64}}:
 1.0    ⋅    ⋅     ⋅    ⋅    ⋅ 
 0.0   1.0   ⋅     ⋅    ⋅    ⋅ 
 0.0   0.0  1.0    ⋅    ⋅    ⋅ 
 1.0  -1.0  1.0   1.0   ⋅    ⋅ 
 1.0   0.0  0.0   1.0  1.0   ⋅ 
 0.0   1.0  0.0  -0.0  1.0  1.0

In [101]:
U

6×6 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  0.0   1.0   0.0   0.0
  ⋅   1.0  1.0   0.0   1.0   0.0
  ⋅    ⋅   1.0   1.0   0.0   1.0
  ⋅    ⋅    ⋅   -1.0   2.0  -1.0
  ⋅    ⋅    ⋅     ⋅   -1.0   2.0
  ⋅    ⋅    ⋅     ⋅     ⋅   -1.0

In [102]:
inv(L)

6×6 LowerTriangular{Float64, Matrix{Float64}}:
  1.0    ⋅     ⋅     ⋅     ⋅    ⋅ 
  0.0   1.0    ⋅     ⋅     ⋅    ⋅ 
  0.0   0.0   1.0    ⋅     ⋅    ⋅ 
 -1.0   1.0  -1.0   1.0    ⋅    ⋅ 
  0.0  -1.0   1.0  -1.0   1.0   ⋅ 
  0.0   0.0  -1.0   1.0  -1.0  1.0

In [103]:
L * inv(L)

6×6 LowerTriangular{Float64, Matrix{Float64}}:
 1.0   ⋅    ⋅    ⋅    ⋅    ⋅ 
 0.0  1.0   ⋅    ⋅    ⋅    ⋅ 
 0.0  0.0  1.0   ⋅    ⋅    ⋅ 
 0.0  0.0  0.0  1.0   ⋅    ⋅ 
 0.0  0.0  0.0  0.0  1.0   ⋅ 
 0.0  0.0  0.0  0.0  0.0  1.0

In [105]:
inv(U)

6×6 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  -1.0   1.0   2.0   3.0   5.0
  ⋅    1.0  -1.0  -1.0  -1.0  -2.0
  ⋅     ⋅    1.0   1.0   2.0   4.0
  ⋅     ⋅     ⋅   -1.0  -2.0  -3.0
  ⋅     ⋅     ⋅     ⋅   -1.0  -2.0
  ⋅     ⋅     ⋅     ⋅     ⋅   -1.0

In [106]:
# Question 5

In [109]:
function lufact2(A)
    A_T = A'
    L, U = lufact(A_T)
    return U', L'
end

lufact2 (generic function with 1 method)

In [114]:
L, U = lufact2(A)

([1.0 0.0 … 0.0 0.0; 0.0 1.0 … 0.0 0.0; … ; 1.0 0.0 … -1.0 0.0; 0.0 1.0 … -1.0 -1.0], [1.0 1.0 … 0.0 0.0; 0.0 1.0 … 1.0 0.0; … ; 0.0 0.0 … 1.0 -2.0; 0.0 0.0 … 0.0 1.0])

In [115]:
L

6×6 LowerTriangular{Float64, Adjoint{Float64, Matrix{Float64}}}:
 1.0    ⋅    ⋅     ⋅     ⋅     ⋅ 
 0.0   1.0   ⋅     ⋅     ⋅     ⋅ 
 0.0   0.0  1.0    ⋅     ⋅     ⋅ 
 1.0  -1.0  1.0  -1.0    ⋅     ⋅ 
 1.0   0.0  0.0  -1.0  -1.0    ⋅ 
 0.0   1.0  0.0   0.0  -1.0  -1.0

In [116]:
U

6×6 UpperTriangular{Float64, Adjoint{Float64, Matrix{Float64}}}:
 1.0  1.0  0.0  1.0   0.0   0.0
  ⋅   1.0  1.0  0.0   1.0   0.0
  ⋅    ⋅   1.0  1.0   0.0   1.0
  ⋅    ⋅    ⋅   1.0  -2.0   1.0
  ⋅    ⋅    ⋅    ⋅    1.0  -2.0
  ⋅    ⋅    ⋅    ⋅     ⋅    1.0